- name: Add the repository for MySql 5.6
  become: yes
  command: add-apt-repository 'deb http://archive.ubuntu.com/ubuntu trusty universe'

- name: Update
  become: yes
  command: apt-get update

- name: Install mysql
  apt: pkg={{ item }} state=installed
  become: true
  with_items:    
    - mysql-server-5.6
    - mysql-client-5.6
    - python-mysqldb
    - libmysqlclient-dev

- name : Ensure mysql started
  become: yes
  service: name=mysql state=started enabled=yes

- name: Update MySQL root password for all root accounts
  mysql_user: name=root 
              host={{ item }} 
              password={{ mysql_root_password }}
              login_user=root
              login_password=""
              state=present
  with_items:
    - 127.0.0.1
    - ::1
    - localhost